version: 2.1

jobs:
  build:
    working_directory: ~/request-provider
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: ls -al ~/request-provider
      - run: yarn install
      - run: yarn --version
      - run: npm run test
